version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto14
    commands:
      - curl -o /bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.16.0/bin/linux/amd64/kubectl
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
      - wget -qO- https://get.helm.sh/helm-v3.5.2-linux-amd64.tar.gz | tar xvz
      - mv linux-amd64/helm /bin/helm
      - chmod +x /bin/kubectl /bin/helm ./aws-iam-authenticator
      - export PATH=$PWD/:$PATH
      - apt-get update && apt-get -y install jq python3-pip python3-dev && pip3 install --upgrade awscli

  pre_build:
    commands:
      - echo connecting ecr
      - docker login -u AWS -p $(aws ecr-public get-login-password --region us-east-1) public.ecr.aws/i2c7a5l2/ot5-gabrielgrazziani/key-manager-grpc
      - sh gradlew build --warning-mode=all
      - echo exporting kubeconfig
      - export KUBECONFIG=$HOME/.kube/config

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t key-manager-grpc .
      - docker tag key-manager-grpc:latest public.ecr.aws/i2c7a5l2/ot5-gabrielgrazziani/key-manager-grpc:latest
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Pushing in to Amazon ECR...
      - docker push public.ecr.aws/i2c7a5l2/ot5-gabrielgrazziani/key-manager-grpc:latest
      - echo Push completed on `date`
      - echo deploying to cluster...
      - helm version --short
      - helm lint pipeline/helm/key-manager-grpc --values pipeline/helm/key-manager-grpc/values.yaml -n gabriel
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region us-east-1 --role-arn arn:aws:iam::208471844409:role/CodeBuildKubectlRole
      - helm upgrade -i key-manager-grpc pipeline/helm/key-manager-grpc/ --values pipeline/helm/key-manager-grpc/values.yaml -n gabriel
