micronaut:
  application:
    name: keyManagerGRPC
datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/key_manager_db`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:zup}
    password: ${DB_PASSWORD:zuper}
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update

endereco_erp_itau: ${ERP_ITAU:`http://localhost:9091/api/v1`}
endereco_banco_central: ${BANCO_CENTRAL:`http://localhost:8082/api/v1`}
