micronaut:
  application:
    name: keyManagerGRPC
datasources:
  default:
    url: jdbc:postgresql://${DB_HOST:`localhost:5432`}/${DB_DATABASE:key_manager_db}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:zup}
    password: ${DB_PASSWORD:zuper}
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update

endereco_erp_itau: ${ERP_ITAU:`http://localhost:9091/api/v1`}
endereco_banco_central: ${BANCO_CENTRAL:`http://localhost:8082/api/v1`}
